run_type = "staged_learning"
device = "cuda:0"
tb_logdir = "tb_stage1"
json_out_config = "_stage1.json"

[parameters]
use_checkpoint = false
summary_csv_prefix = "rl_stage1"
agent_file = "REINVENT4/priors/reinvent.prior"
prior_file = "REINVENT4/priors/reinvent.prior"

batch_size = 200

[learning_strategy]

type = "dap"
sigma = 128
rate = 0.0005

[[stage]]
max_score = 1.0
chkpt_file = 'rl_direct.chkpt'
termination = "simple"
max_steps = 100

[stage.scoring]
type = "geometric_mean"

[[stage.scoring.component]]
[stage.scoring.component.MelaninBinding]
[[stage.scoring.component.MelaninBinding.endpoint]]
name="MelaninBinding"
weight=1

[[stage.scoring.component]]
[stage.scoring.component.Irritation]
[[stage.scoring.component.Irritation.endpoint]]
name="Irritation"
weight=1

[[stage.scoring.component]]
[stage.scoring.component.CornealPermeabilityNorm]
[[stage.scoring.component.CornealPermeabilityNorm.endpoint]]
name="CornealPermeabilityNorm"
weight=1

[[stage.scoring.component]]
[stage.scoring.component.QED]
[[stage.scoring.component.QED.endpoint]]
name = "QED"
weight = 0.5

[[stage.scoring.component]]
[stage.scoring.component.SAScore]
[[stage.scoring.component.SAScore.endpoint]]
name = "SAScore"
weight = 0.5

